INSERT INTO tb_category(name, created_At) VALUES('Books', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Electronics', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Computers', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Smartphones', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Tablets', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Laptops', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Desktops', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Monitors', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Headphones', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Speakers', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Cameras', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Video Games', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Consoles', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Accessories', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Software', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Office Supplies', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Furniture', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Home Appliances', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Kitchen', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Clothing', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Shoes', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Sports', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Fitness', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Health', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Beauty', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Toys', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Board Games', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Movies', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Music', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Instruments', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Garden', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Tools', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Automotive', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Motorcycles', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Pet Supplies', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Baby Products', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Jewelry', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Watches', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Bags', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Travel', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Stationery', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Photography', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Drones', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Smart Home', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Lighting', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Energy', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Security', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Streaming Devices', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Virtual Reality', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Artificial Intelligence', NOW());
INSERT INTO tb_category(name, created_At) VALUES('3D Printing', NOW());